services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-shared
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - qdrant-net

networks:
  qdrant-net:
    name: qdrant-shared-network
    external: true

volumes:
  qdrant_storage:
    name: qdrant-persistent-storage